/// <reference path="./_references.ts"/>

window.jsCommon = window.jsCommon || {};
window.powerbi = window.powerbi || {};
window.debug = window.debug || {};
window.InJs = window.InJs || {};
window.Microsoft = window.Microsoft || {};

// require("script!../../.././lib/powerbi-visuals-externals.min.js");

require("../Externals/ThirdPartyIP/jqueryui/1.11.4/jquery-ui.min.css");
require("./styles/visuals.less");

require("file?name=images/[name].[ext]!./images/locationButton.svg");

// require("../VisualsContracts/module.ts");
// require("../VisualsExtensibility/module.ts");
// require("../VisualsCommon/module.ts");
// require("../VisualsData/module.ts");

// require("../CustomVisuals/module.ts");

require("./typedefs/typedefs.ts");
require("./common/point.ts");
require("./common/rect.ts");
require("./legend.ts");
require("./types/axisScale.ts");
require("./types/axisStyle.ts");
require("./types/axisType.ts");
require("./types/basicShapeType.ts");
require("./types/imageScalingType.ts");
require("./types/labelPosition.ts");
require("./types/labelStyle.ts");
require("./types/legendPosition.ts");
require("./types/kpi_direction_type.ts");
require("./types/lineStyle.ts");
require("./types/outline.ts");
require("./types/referenceLinePosition.ts");
require("./types/slicerOrientation.ts");
require("./types/yAxisPosition.ts");
require("./animators/animatorCommon.ts");
require("./animators/columnChartAnimator.ts");
require("./animators/donutChartAnimator.ts");
require("./animators/funnelChartAnimator.ts");
require("./animators/treemapAnimator.ts");
require("./capabilities/dataViewObjectProperties.ts");
require("./capabilities/animatedNumber.capabilities.ts");
require("./capabilities/basicShape.capabilities.ts");
require("./capabilities/columnChart.capabilities.ts");
require("./capabilities/comboChart.capabilities.ts");
require("./capabilities/donutChart.capabilities.ts");
require("./capabilities/dataDotChart.capabilities.ts");
require("./capabilities/filledMap.capabilities.ts");
require("./capabilities/funnelChart.capabilities.ts");
require("./capabilities/gauge.capabilities.ts");
require("./capabilities/imageVisual.capabilities.ts");
require("./capabilities/scriptVisual.capabilities.ts");
require("./capabilities/samples/consoleWriter.capabilities.ts");
require("./visuals/samples/consoleWriter.ts");
require("./capabilities/lineChart.capabilities.ts");
require("./capabilities/map.capabilities.ts");
require("./capabilities/multiRowCard.capabilities.ts");
require("./capabilities/textbox.capabilities.ts");
require("./capabilities/sampleVisual.capabilities.ts");
require("./capabilities/scatterChart.capabilities.ts");
require("./capabilities/slicer.capabilities.ts");
require("./capabilities/table.capabilities.ts");
require("./capabilities/matrix.capabilities.ts");
require("./capabilities/treemap.capabilities.ts");
require("./capabilities/card.capabilities.ts");
require("./capabilities/waterfallChart.capabilities.ts");
require("./capabilities/kpiStatusWithHistory.capabilities.ts");
require("./pluginsCapabilities.ts");
require("./behaviours/columnChartBehaviors.ts");
require("./behaviours/dataDotChartBehavior.ts");
require("./behaviours/donutChartBehaviors.ts");
require("./behaviours/funnelBehaviors.ts");
require("./behaviours/playChartBehaviors.ts");
require("./behaviours/lineChartBehaviors.ts");
require("./behaviours/mapBehaviors.ts");
require("./behaviours/scatterChartBehaviors.ts");
require("./behaviours/horizontalSlicerBehaviors.ts");
require("./behaviours/verticalSlicerBehaviors.ts");
require("./behaviours/slicerBehaviors.ts");
require("./behaviours/legendBehaviors.ts");
require("./behaviours/treemapBehaviors.ts");
require("./behaviours/waterfallChartBehavior.ts");
require("./behaviours/LabelsBehavior.ts");
require("./behaviours/cartesianChartBehaviors.ts");
require("./contracts/contracts.ts");
require("./common/axisHelper.ts");
require("./common/basicShapeUtils.ts");
require("./common/cartesianHelper.ts");
require("./common/colorHelper.ts");
require("./common/columnChartUtil.ts");
require("./common/converterHelper.ts");
require("./common/dataLabelUtils.ts");
require("./common/donutLabelUtils.ts");
require("./common/newDataLabelUtils.ts");
require("./common/kpiUtil.ts");
require("./common/referenceLineHelper.ts");
require("./common/interactivityUtils.ts");
require("./common/invalidDataValuesChecker.ts");
require("./common/listView.ts");
require("./common/mapUtil.ts");
require("./common/selectionManager.ts");
require("./common/shapes.ts");
require("./common/slicerUtil.ts");
require("./common/tooltipUtils.ts");
require("./common/svgUtil.ts");
require("./common/textUtil.ts");
require("./common/gradientHelper.ts");
require("./common/visualBackgroundHelper.ts");
require("./common/objectEnumerationBuilder.ts");
require("./common/visualBorderUtil.ts");
require("./common/transform.ts");
require("./common/trendLineHelper.ts");
require("./common/visibilityUtil.ts");
require("./common/visualObjectRepetition.ts");
require("./converter/slicer.converter.ts");
require("./formatting/dataLabelManager.ts");
require("./formatting/labelLayout.ts");
require("./formatting/donutLabelLayout.ts");
require("./formatting/filledMapLabelLayout.ts");
require("./services/colorAllocatorFactory.ts");
require("./services/defaultVisualHostService.ts");
require("./services/interactivityService.ts");
require("./services/geocoder.ts");
require("./services/geocodingCache.ts");
require("./services/geolocationService.ts");
require("./services/visualPluginService.ts");
require("./controls/scrollbar/scrollbar.ts");
require("./controls/tablix/internal/tablixGridPresenter.ts");
require("./controls/tablix/internal/tablixRealizationManager.ts");
require("./controls/tablix/internal/tablixGrid.ts");
require("./controls/tablix/internal/tablixLayoutManager.ts");
require("./controls/tablix/internal/tablixUtils.ts");
require("./controls/tablix/iTablixHierarchyNavigator.ts");
require("./controls/tablix/iTablixBinder.ts");
require("./controls/tablix/iTablixLayoutManager.ts");
require("./controls/tablix/tablixControl.ts");
require("./controls/tablix/tablixDimension.ts");
require("./controls/tablix/tablixTouchDelegate.ts");
require("./controls/tablix/touchRegionAbstraction.ts");
require("./controls/tablix/ITablixFormatting.ts");
require("./controls/tablix/tablixColumnWidthManager.ts");
require("./visuals/animatedText.ts");
require("./visuals/animatedNumber.ts");
require("./visuals/basicShape.ts");
require("./cartesian/cartesianChart.ts");
require("./cartesian/columnChart.ts");
require("./cartesian/columnChartClustered.ts");
require("./cartesian/columnChartStacked.ts");
require("./visuals/samples/helloIVisual.ts");
require("./cartesian/comboChart.ts");
require("./dataColorPalette.ts");
require("./cartesian/dataDotChart.ts");
require("./visuals/funnelChart.ts");
require("./visuals/gauge.ts");
require("./visuals/imageVisual.ts");
require("./visuals/kpiStatusWithHistory.ts");
require("./cartesian/lineChart.ts");
require("./visuals/map.ts");
require("./visuals/multiRowCard.ts");
require("./visuals/textbox.ts");
require("./visuals/sampleVisual.ts");
require("./cartesian/scatterChart.ts");
require("./cartesian/playChart.ts");
require("./visuals/verticalSlicer.ts");
require("./visuals/horizontalSlicer.ts");
require("./visuals/slicer.ts");
require("./visuals/table.ts");
require("./visuals/matrix.ts");
require("./visuals/treemap.ts");
require("./visuals/card.ts");
require("./visuals/owlGauge.ts");
require("./warnings/visualWarnings.ts");
require("./cartesian/waterfallChart.ts");
require("./tooltip.ts");
require("./styles/visualStyles.ts");
require("./visuals/donutChart.ts");
require("./visuals/scriptVisual.ts");
require("./visuals/system/debugVisual.ts");
require("./plugins.ts");
require("./common/canvasBackgroundHelper.ts");
